#!/usr/bin/env nu

const corpus_dir = $"($nu.home-dir)/iWork/refs/brotli/tests/testdata"
const temp_file = "src/brotli_conformance_wbtest.mbt"
const harness_lock_dir = "tools/.harness-lock"

def process-alive [pid: int]: nothing -> bool {
  let probe = (^ps -p ($pid | into string) | complete)
  $probe.exit_code == 0
}

def lock-pid-path []: nothing -> string {
  $harness_lock_dir | path join "pid"
}

def stale-harness-lock []: nothing -> bool {
  let pid_path = (lock-pid-path)
  if not ($pid_path | path exists) {
    true
  } else {
    try {
      let pid = (open --raw $pid_path | str trim | into int)
      not (process-alive $pid)
    } catch {
      true
    }
  }
}

def write-lock-pid []: nothing -> nothing {
  $nu.pid | into string | save --force (lock-pid-path)
}

def acquire-harness-lock []: nothing -> nothing {
  let made = (^mkdir $harness_lock_dir | complete)
  if $made.exit_code != 0 {
    if (stale-harness-lock) {
      rm --force --recursive $harness_lock_dir
      let retry = (^mkdir $harness_lock_dir | complete)
      if $retry.exit_code == 0 {
        write-lock-pid
      } else {
        print --stderr "Another Brotli harness is running; retry after it finishes."
        exit 1
      }
    } else {
      let pid_path = (lock-pid-path)
      let owner = if ($pid_path | path exists) { open --raw $pid_path | str trim } else { "unknown" }
      print --stderr $"Another Brotli harness is running \(pid: ($owner)\); retry after it finishes."
      exit 1
    }
  } else {
    write-lock-pid
  }
}

def release-harness-lock []: nothing -> nothing {
  rm --force --recursive $harness_lock_dir
}

def sanitize-name [name: string]: nothing -> string {
  $name | str replace --all --regex '[^A-Za-z0-9_]' '_'
}

def byte-tokens [path: string]: nothing -> list<string> {
  let encoded = (
    open --raw $path
    | into binary
    | to nuon
    | str trim --char '"'
    | str replace '0x[' ''
    | str replace ']' ''
  )

  if ($encoded | str length) == 0 {
    []
  } else {
    $encoded
    | split chars
    | chunks 2
    | each {|pair| $"0x($pair | str join | str downcase)" }
  }
}

def moon-byte-array [path: string]: nothing -> string {
  let tokens = byte-tokens $path
  if ($tokens | length) == 0 {
    "FixedArray::make(0, b'\\x00')"
  } else {
    let body = (
      $tokens
      | chunks 16
      | each {|chunk| $"  ($chunk | str join ', ')," }
      | str join (char newline)
    )
    $"[((char newline))($body)((char newline))]"
  }
}

def corpus-fixtures []: nothing -> list<record> {
  glob ($corpus_dir | path join "*.compressed")
  | sort
  | each {|compressed_path|
      let compressed_name = ($compressed_path | path basename)
      let expected_name = ($compressed_name | str replace ".compressed" "")
      let expected_path = ($corpus_dir | path join $expected_name)
      if ($expected_path | path exists) {
        {
          name: $expected_name
          test_name: (sanitize-name $expected_name)
          compressed_path: $compressed_path
          expected_path: $expected_path
        }
      } else {
        null
      }
    }
  | compact
}

def write-temp-test [fixture: record]: nothing -> string {
  let compressed = moon-byte-array $fixture.compressed_path
  let expected = moon-byte-array $fixture.expected_path
  let test_name = $"brotli conformance ($fixture.name)"
  let source = (
    [
      "// Generated by tools/conformance/run.nu."
      "// This file is temporary and should not be committed."
      ""
      "///|"
      $"let brotli_conformance_compressed : FixedArray[Byte] = ($compressed)"
      ""
      "///|"
      $"let brotli_conformance_expected : FixedArray[Byte] = ($expected)"
      ""
      "///|"
      $"test \"($test_name)\" {"
      "  let result : Result[FixedArray[Byte], FbrError] = try? unbrotli_sync(brotli_conformance_compressed)"
      "  guard result is Ok(actual) else {"
      "    guard result is Err(FbrError(code~, message~)) else {"
      "      fail(\"expected Brotli conformance decode result\")"
      "    }"
      "    fail(\"brotli conformance decode failed: \\{code}: \\{message}\")"
      "  }"
      "  assert_eq(actual.length(), brotli_conformance_expected.length())"
      "  for i in 0..<brotli_conformance_expected.length() {"
      "    assert_eq(actual[i], brotli_conformance_expected[i])"
      "  }"
      "}"
      ""
    ]
    | str join (char newline)
  )
  $source | save --force $temp_file
  $test_name
}

def write-placeholder-temp-test []: nothing -> nothing {
  [
    "// Placeholder for tools/conformance/run.nu."
    "// The harness rewrites this ignored file during a conformance run."
    ""
  ] | str join (char newline) | save --force $temp_file
}

def run-fixture [fixture: record]: nothing -> record {
  let test_name = write-temp-test $fixture
  let run = (moon test --target native --filter $test_name | complete)
  let ok = $run.exit_code == 0
  if not $ok {
    print --stderr $run.stdout
    print --stderr $run.stderr
  }
  {
    fixture: $fixture.name
    ok: $ok
    exit_code: $run.exit_code
  }
}

def main [
  --fixture (-f): string # Run one corpus fixture by expected-file name.
]: nothing -> nothing {
  acquire-harness-lock
  let all_fixtures = corpus-fixtures
  let fixtures = if $fixture == null {
    $all_fixtures
  } else {
    $all_fixtures | where name == $fixture
  }

  if ($fixtures | length) == 0 {
    print --stderr "No matching Brotli conformance fixtures."
    release-harness-lock
    exit 1
  }

  # Keep fixture execution sequential because every case rewrites the same
  # temporary white-box test file.
  let results = (
    $fixtures
    | generate {|fixture, state=null|
      {
        out: (run-fixture $fixture)
        next: $state
      }
    }
  )

  write-placeholder-temp-test
  print ($results | table)
  if ($results | any {|row| not $row.ok }) {
    release-harness-lock
    exit 1
  }
  release-harness-lock
}
