#!/usr/bin/env nu

const temp_file = "src/brotli_roundtrip_fuzz_wbtest.mbt"
const harness_lock_dir = "tools/.harness-lock"
const default_batch_size = 25
const default_qualities = "0,1,2,9,11"

def process-alive [pid: int]: nothing -> bool {
  let probe = (^ps -p ($pid | into string) | complete)
  $probe.exit_code == 0
}

def lock-pid-path []: nothing -> string {
  $harness_lock_dir | path join "pid"
}

def stale-harness-lock []: nothing -> bool {
  let pid_path = (lock-pid-path)
  if not ($pid_path | path exists) {
    true
  } else {
    try {
      let pid = (open --raw $pid_path | str trim | into int)
      not (process-alive $pid)
    } catch {
      true
    }
  }
}

def write-lock-pid []: nothing -> nothing {
  $nu.pid | into string | save --force (lock-pid-path)
}

def acquire-harness-lock []: nothing -> nothing {
  let made = (^mkdir $harness_lock_dir | complete)
  if $made.exit_code != 0 {
    if (stale-harness-lock) {
      rm --force --recursive $harness_lock_dir
      let retry = (^mkdir $harness_lock_dir | complete)
      if $retry.exit_code == 0 {
        write-lock-pid
      } else {
        print --stderr "Another Brotli harness is running; retry after it finishes."
        exit 1
      }
    } else {
      let pid_path = (lock-pid-path)
      let owner = if ($pid_path | path exists) { open --raw $pid_path | str trim } else { "unknown" }
      print --stderr $"Another Brotli harness is running \(pid: ($owner)\); retry after it finishes."
      exit 1
    }
  } else {
    write-lock-pid
  }
}

def release-harness-lock []: nothing -> nothing {
  rm --force --recursive $harness_lock_dir
}

def parse-qualities [qualities: string]: nothing -> list<int> {
  $qualities
  | split row ","
  | each {|q| $q | str trim | into int }
}

def generated-helper-source []: nothing -> string {
  [
    "fn brotli_roundtrip_fuzz_input(length : Int, seed : Int) -> FixedArray[Byte] {"
    "  let data = FixedArray::make(length, b'\\x00')"
    "  for i in 0..<length {"
    "    let mixed = (i * 131 + seed * 17 + (i / 7) * 29) & 255"
    "    data[i] = mixed.to_byte()"
    "  }"
    "  data"
    "}"
    ""
    "///|"
    "fn brotli_roundtrip_fuzz_case(length : Int, seed : Int, quality : Int) -> Unit raise {"
    "  let input = brotli_roundtrip_fuzz_input(length, seed)"
    "  let compressed = brotli_sync(input, opts={"
    "    quality,"
    "    window_bits: 16,"
    "    max_input_size: default_max_input_size,"
    "  })"
    "  let decoded = unbrotli_sync(compressed)"
    "  assert_eq(decoded.length(), input.length())"
    "  for i in 0..<input.length() {"
    "    assert_eq(decoded[i], input[i])"
    "  }"
    "}"
    ""
  ] | str join (char newline)
}

def case-length [index: int, max_len: int]: nothing -> int {
  if $index == 0 {
    0
  } else {
    (($index * 173 + 19) mod $max_len) + 1
  }
}

def roundtrip-cases [count: int, max_len: int, qualities: list<int>]: nothing -> list<record> {
  0..<$count
  | each {|index|
    let length = case-length $index $max_len
    let seed = $index + 1
    $qualities
    | each {|quality|
      {
        index: $index
        length: $length
        seed: $seed
        quality: $quality
      }
    }
  }
  | flatten
}

def test-source [case: record batch_index: int]: nothing -> string {
  let test_name = $"brotli roundtrip fuzz batch ($batch_index) case ($case.index) q($case.quality)"
  let length = $case.length
  let seed = $case.seed
  let quality = $case.quality
  [
    "///|"
    $"test \"($test_name)\" {"
    ([
      "  brotli_roundtrip_fuzz_case("
      ($length | into string)
      ", "
      ($seed | into string)
      ", "
      ($quality | into string)
      ")"
    ] | str join)
    "}"
    ""
  ] | str join (char newline)
}

def write-temp-tests [cases: list<record> batch_index: int]: nothing -> string {
  let body = (
    $cases
    | enumerate
    | each {|entry| test-source $entry.item $batch_index }
    | str join (char newline)
  )
  let source = (
    [
      "// Generated by tools/fuzz/roundtrip.nu."
      "// This file is temporary and should not be committed."
      ""
      "///|"
      (generated-helper-source)
      $body
    ]
    | str join (char newline)
  )
  $source | save --force $temp_file
  $"brotli roundtrip fuzz batch ($batch_index) *"
}

def write-placeholder-temp-tests []: nothing -> nothing {
  [
    "// Placeholder for tools/fuzz/roundtrip.nu."
    "// The harness rewrites this ignored file during an encoder fuzz run."
    ""
  ] | str join (char newline) | save --force $temp_file
}

def run-batch [batch: record, target: string]: nothing -> list<record> {
  let filter = write-temp-tests $batch.item $batch.index
  let run = (moon test --target $target --filter $filter | complete)
  let ok = $run.exit_code == 0
  if not $ok {
    print --stderr $run.stdout
    print --stderr $run.stderr
  }
  $batch.item
  | each {|case|
    {
      case: $case.index
      length: $case.length
      quality: $case.quality
      batch: $batch.index
      target: $target
      ok: $ok
      exit_code: $run.exit_code
    }
  }
}

def run-batches [
  cases: list<record>
  batch_size: int
  target: string
]: nothing -> list<record> {
  # generate keeps each moon test run ordered because batches share one
  # generated white-box test file.
  $cases
  | chunks $batch_size
  | enumerate
  | generate {|batch, state=null|
    {
      out: (run-batch $batch $target)
      next: $state
    }
  }
  | flatten
}

def main [
  --count (-n): int = 12
  --max-len: int = 2048
  --qualities (-q): string = $default_qualities
  --batch-size (-b): int = $default_batch_size
  --target (-t): string = "native"
]: nothing -> nothing {
  acquire-harness-lock
  if $count <= 0 {
    print --stderr "Count must be greater than zero."
    release-harness-lock
    exit 1
  }
  if $max_len <= 0 {
    print --stderr "Max length must be greater than zero."
    release-harness-lock
    exit 1
  }
  if $batch_size <= 0 {
    print --stderr "Batch size must be greater than zero."
    release-harness-lock
    exit 1
  }

  let parsed_qualities = parse-qualities $qualities
  let cases = roundtrip-cases $count $max_len $parsed_qualities

  let results = run-batches $cases $batch_size $target

  write-placeholder-temp-tests
  print ($results | table)
  if ($results | any {|row| not $row.ok }) {
    release-harness-lock
    exit 1
  }
  release-harness-lock
}
