#!/usr/bin/env nu

const default_corpus_dir = "tools/brotli/fuzz/corpus"
const temp_file = "src/brotli_fuzz_wbtest.mbt"
const harness_lock_dir = "tools/brotli/.harness-lock"

def acquire-harness-lock []: nothing -> nothing {
  let made = (^mkdir $harness_lock_dir | complete)
  if $made.exit_code != 0 {
    print --stderr "Another Brotli harness is running; retry after it finishes."
    exit 1
  }
}

def release-harness-lock []: nothing -> nothing {
  rm --force --recursive $harness_lock_dir
}

def sanitize-name [name: string]: nothing -> string {
  $name | str replace --all --regex '[^A-Za-z0-9_]' '_'
}

def byte-tokens [path: string]: nothing -> list<string> {
  let encoded = (
    open --raw $path
    | into binary
    | to nuon
    | str trim --char '"'
    | str replace '0x[' ''
    | str replace ']' ''
  )

  if ($encoded | str length) == 0 {
    []
  } else {
    $encoded
    | split chars
    | chunks 2
    | each {|pair| $"0x($pair | str join | str downcase)" }
  }
}

def moon-byte-array [path: string]: nothing -> string {
  let tokens = byte-tokens $path
  if ($tokens | length) == 0 {
    "FixedArray::make(0, b'\\x00')"
  } else {
    let body = (
      $tokens
      | chunks 16
      | each {|chunk| $"  ($chunk | str join ', ')," }
      | str join (char newline)
    )
    $"[((char newline))($body)((char newline))]"
  }
}

def corpus-files [corpus_dir: string]: nothing -> list<string> {
  glob ($corpus_dir | path join "*.br")
  | append (glob ($corpus_dir | path join "*.bin"))
  | append (glob ($corpus_dir | path join "*.mut"))
  | sort
}

def write-temp-test [path: string]: nothing -> string {
  let input = moon-byte-array $path
  let name = sanitize-name ($path | path basename)
  let test_name = $"brotli fuzz ($name)"
  let source = (
    [
      "// Generated by tools/brotli/fuzz/run.nu."
      "// This file is temporary and should not be committed."
      ""
      "///|"
      $"let brotli_fuzz_input : FixedArray[Byte] = ($input)"
      ""
      "///|"
      $"test \"($test_name)\" {"
      "  let result : Result[FixedArray[Byte], FzipError] = try? unbrotli_sync(brotli_fuzz_input)"
      "  match result {"
      "    Ok(_) => ()"
      "    Err(_) => ()"
      "  }"
      "}"
      ""
    ]
    | str join (char newline)
  )
  $source | save --force $temp_file
  $test_name
}

def main [
  --corpus-dir (-c): string = $default_corpus_dir
  --limit (-n): int = 0
]: nothing -> nothing {
  acquire-harness-lock
  let files = corpus-files $corpus_dir
  let selected = if $limit > 0 {
    $files | first $limit
  } else {
    $files
  }

  if ($selected | length) == 0 {
    print --stderr $"No Brotli fuzz inputs found in ($corpus_dir)."
    release-harness-lock
    exit 1
  }

  mut results = []
  for path in $selected {
    let test_name = write-temp-test $path
    let run = (moon test --target native --filter $test_name | complete)
    let ok = $run.exit_code == 0
    if not $ok {
      print --stderr $run.stdout
      print --stderr $run.stderr
    }
    $results = ($results | append {
      input: ($path | path basename)
      ok: $ok
      exit_code: $run.exit_code
    })
  }

  rm --force $temp_file
  print ($results | table)
  if ($results | any {|row| not $row.ok }) {
    release-harness-lock
    exit 1
  }
  release-harness-lock
}
