#!/usr/bin/env nu

const default_corpus_dir = "tools/brotli/fuzz/corpus"
const temp_file = "src/brotli_fuzz_wbtest.mbt"
const harness_lock_dir = "tools/brotli/.harness-lock"
const default_batch_size = 25

def acquire-harness-lock []: nothing -> nothing {
  let made = (^mkdir $harness_lock_dir | complete)
  if $made.exit_code != 0 {
    print --stderr "Another Brotli harness is running; retry after it finishes."
    exit 1
  }
}

def release-harness-lock []: nothing -> nothing {
  rm --force --recursive $harness_lock_dir
}

def sanitize-name [name: string]: nothing -> string {
  $name | str replace --all --regex '[^A-Za-z0-9_]' '_'
}

def byte-tokens [path: string]: nothing -> list<string> {
  let encoded = (
    open --raw $path
    | into binary
    | to nuon
    | str trim --char '"'
    | str replace '0x[' ''
    | str replace ']' ''
  )

  if ($encoded | str length) == 0 {
    []
  } else {
    $encoded
    | split chars
    | chunks 2
    | each {|pair| $"0x($pair | str join | str downcase)" }
  }
}

def moon-byte-array [path: string]: nothing -> string {
  let tokens = byte-tokens $path
  if ($tokens | length) == 0 {
    "FixedArray::make(0, b'\\x00')"
  } else {
    let body = (
      $tokens
      | chunks 16
      | each {|chunk| $"  ($chunk | str join ', ')," }
      | str join (char newline)
    )
    $"[((char newline))($body)((char newline))]"
  }
}

def corpus-files [corpus_dir: string]: nothing -> list<string> {
  glob ($corpus_dir | path join "*.br")
  | append (glob ($corpus_dir | path join "*.bin"))
  | append (glob ($corpus_dir | path join "*.mut"))
  | sort
}

def test-source [path: string index: int batch_index: int]: nothing -> string {
  let input = moon-byte-array $path
  let input_name = $"brotli_fuzz_input_($index)"
  let name = sanitize-name ($path | path basename)
  let test_name = $"brotli fuzz batch ($batch_index) ($name)"
  [
    "///|"
    $"let ($input_name) : FixedArray[Byte] = ($input)"
    ""
    "///|"
    $"test \"($test_name)\" {"
    ([
      "  let result : Result[FixedArray[Byte], FzipError] = try? unbrotli_sync("
      $input_name
      ")"
    ] | str join)
    "  match result {"
    "    Ok(_) => ()"
    "    Err(_) => ()"
    "  }"
    "}"
    ""
  ] | str join (char newline)
}

def write-temp-tests [paths: list<string> batch_index: int]: nothing -> string {
  let body = (
    $paths
    | enumerate
    | each {|entry| test-source $entry.item $entry.index $batch_index }
    | str join (char newline)
  )
  let source = (
    [
      "// Generated by tools/brotli/fuzz/run.nu."
      "// This file is temporary and should not be committed."
      ""
      $body
    ]
    | str join (char newline)
  )
  $source | save --force $temp_file
  $"brotli fuzz batch ($batch_index) *"
}

def main [
  --corpus-dir (-c): string = $default_corpus_dir
  --limit (-n): int = 0
  --batch-size (-b): int = $default_batch_size
  --target (-t): string = "native"
]: nothing -> nothing {
  acquire-harness-lock
  let files = corpus-files $corpus_dir
  let selected = if $limit > 0 {
    $files | first $limit
  } else {
    $files
  }

  if ($selected | length) == 0 {
    print --stderr $"No Brotli fuzz inputs found in ($corpus_dir)."
    release-harness-lock
    exit 1
  }

  if $batch_size <= 0 {
    print --stderr "Batch size must be greater than zero."
    release-harness-lock
    exit 1
  }

  mut results = []
  for batch in ($selected | chunks $batch_size | enumerate) {
    let filter = write-temp-tests $batch.item $batch.index
    let run = (moon test --target $target --filter $filter | complete)
    let ok = $run.exit_code == 0
    if not $ok {
      print --stderr $run.stdout
      print --stderr $run.stderr
    }
    let batch_results = (
      $batch.item
      | each {|path|
        {
          input: ($path | path basename)
          batch: $batch.index
          target: $target
          ok: $ok
          exit_code: $run.exit_code
        }
      }
    )
    $results = ($results | append $batch_results)
  }

  rm --force $temp_file
  print ($results | table)
  if ($results | any {|row| not $row.ok }) {
    release-harness-lock
    exit 1
  }
  release-harness-lock
}
