#!/usr/bin/env nu

const corpus_dir = $"($nu.home-dir)/iWork/refs/brotli/tests/testdata"
const fixture_dir = "src/tests/brotli_fixtures"
const output_file = "src/brotli_fixture_wbtest.mbt"

const fixtures = [
  {name: "empty", compressed: "empty.compressed", expected: "empty"}
  {name: "10x10y", compressed: "10x10y.compressed", expected: "10x10y"}
  {name: "64x", compressed: "64x.compressed", expected: "64x"}
  {name: "quickfox", compressed: "quickfox.compressed", expected: "quickfox"}
  {
    name: "quickfox_repeated"
    compressed: "quickfox_repeated.compressed"
    expected: "quickfox_repeated"
  }
  {name: "ukkonooa", compressed: "ukkonooa.compressed", expected: "ukkonooa"}
  {name: "monkey", compressed: "monkey.compressed", expected: "monkey"}
  {
    name: "random_org_10k_bin"
    compressed: "random_org_10k.bin.compressed"
    expected: "random_org_10k.bin"
  }
]

def sanitize-name [name: string]: nothing -> string {
  $name | str replace --all --regex '[^A-Za-z0-9_]' '_'
}

def byte-tokens [path: string]: nothing -> list<string> {
  let encoded = (
    open --raw $path
    | into binary
    | to nuon
    | str trim --char '"'
    | str replace '0x[' ''
    | str replace ']' ''
  )

  if ($encoded | str length) == 0 {
    []
  } else {
    $encoded
    | split chars
    | chunks 2
    | each {|pair| $"0x($pair | str join | str downcase)" }
  }
}

def moon-byte-array [path: string]: nothing -> string {
  let tokens = byte-tokens $path
  if ($tokens | length) == 0 {
    "FixedArray::make(0, b'\\x00')"
  } else {
    let body = (
      $tokens
      | chunks 16
      | each {|chunk| $"  ($chunk | str join ', ')," }
      | str join (char newline)
    )
    $"[((char newline))($body)((char newline))]"
  }
}

def fixture-functions [fixture: record]: nothing -> string {
  let name = sanitize-name $fixture.name
  let compressed_path = ($corpus_dir | path join $fixture.compressed)
  let expected_path = ($corpus_dir | path join $fixture.expected)
  let compressed = moon-byte-array $compressed_path
  let expected = if $fixture.name == "quickfox_repeated" {
    "{\n  let phrase = brotli_fixture_quickfox_expected\n  let out = FixedArray::make(phrase.length() * 4096, b'\\x00')\n  for i in 0..<4096 {\n    phrase.blit_to(out, len=phrase.length(), src_offset=0, dst_offset=i * phrase.length())\n  }\n  out\n}"
  } else {
    moon-byte-array $expected_path
  }

  [
    "///|"
    $"let brotli_fixture_($name)_compressed : FixedArray[Byte] = ($compressed)"
    ""
    "///|"
    $"let brotli_fixture_($name)_expected : FixedArray[Byte] = ($expected)"
    ""
    "///|"
    $"test \"brotli fixture ($fixture.name)\" {"
    $"  let compressed = brotli_fixture_($name)_compressed"
    $"  let expected = brotli_fixture_($name)_expected"
    "  let actual = unbrotli_sync(compressed)"
    "  assert_eq(actual.length(), expected.length())"
    "  for i in 0..<expected.length() {"
    "    assert_eq(actual[i], expected[i])"
    "  }"
    "}"
    ""
  ] | str join (char newline)
}

def main []: nothing -> nothing {
  mkdir $fixture_dir

  for fixture in $fixtures {
    cp --force ($corpus_dir | path join $fixture.compressed) (
      $fixture_dir | path join $"($fixture.name).br"
    )
    cp --force ($corpus_dir | path join $fixture.expected) (
      $fixture_dir | path join $"($fixture.name).expected"
    )
  }

  let generated = (
    [
      "// Generated by tools/gen-fixtures.nu from the upstream Brotli test corpus."
      "// Do not edit by hand; rerun the generator after changing fixture selection."
      ""
      ($fixtures | each {|fixture| fixture-functions $fixture } | str join (char newline))
    ]
    | str join (char newline)
  )

  $generated | save --force $output_file
}
