# Description:
#   - Fbr build & test Check

name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - "**.md"
      - "docs/**"
      
permissions: read-all

jobs:
  fbr-check:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: CI@${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: hustcer/setup-moonbit@v1.22

      - name: Check Fbr Build & Test
        run: |
          moon version --all
          moon check --target all
          moon build --target all
          moon test --target all
